### PR TITLE
Run GHA on 10.15 and 11.0

### PR DESCRIPTION
**Pull request by Zialus**

### CODE REVIEW

**Comment by LouisBrunner** [comment]
Hi @Zialus,

I am happy with the addition of the matrix build for macos, but the Linux workflow is still required.

**Review by LouisBrunner — CHANGES_REQUESTED** [review]
Restore Linux building

**Comment by Zialus** [comment]
Hi @LouisBrunner, sorry for the initial state of the PR, I was just quickly hacking something up, directly on the Github UI.

I did a deeper cleanup now and you can check the results @ https://github.com/Zialus/valgrind-macos/actions/runs/1631638961

**Comment by LouisBrunner** [comment]
Thank you @Zialus, that is so much nicer!

**Review by LouisBrunner — APPROVED** [review]

**Pull request merged**
